plugins {
    id 'com.android.application'
}

android {
    namespace 'io.mtop.overcontrol'
    compileSdk 34

    defaultConfig {
        applicationId "io.mtop.overcontrol"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildTypes { release { minifyEnabled false } }
}
